package io.github.twyora.douyinenhancer.config.key

object PlaybackComponentBlockKey {
    const val MAIN_SWITCH = "playback_component_block_main_switch"
    const val MUSIC_COVER_BLOCK = "playback_component_block_music_cover_block"
    const val MUSIC_LISTEN_COVER = "playback_component_block_music_listen_cover"
    const val DIGG = "playback_component_block_digg"
    const val TITLE = "playback_component_block_title"
    const val MUSIC_COVER = "playback_component_block_music_cover"
    const val GENERAL_LABEL = "playback_component_block_general_label"
    const val FEED_LABEL_CONTAINER = "playback_component_block_feed_label_container"
    const val MUSIC_TITLE = "playback_component_block_music_title"
    const val STORY_25_DIVERSE_DIGG = "playback_component_block_story_25_diverse_digg"
    const val ECOM_STORE = "playback_component_block_ecom_store"
    const val BUTTON_IM_QUICK_SHARE = "playback_component_block_button_im_quick_share"
    const val BUTTON_FEED_IM_SHARE_GUIDE_V2 = "playback_component_block_button_feed_im_share_guide_v2"
    const val BUTTON_FORCE_FEED_IM_SHARE_GUIDE = "playback_component_block_button_force_feed_im_share_guide"
    const val SOCIAL_NEW_COMMENT_GUIDE_BUBBLE = "playback_component_block_social_new_comment_guide_bubble"
    const val COMMENT_BOTTOM_ANIMATION = "playback_component_block_comment_bottom_animation"
    const val NEARBY_IDENTITY_TAG = "playback_component_block_nearby_identity_tag"
    const val LIVE_PHOTO_TAG = "playback_component_block_live_photo_tag"
    const val PHOTOS_TAG = "playback_component_block_photos_tag"
    const val STORY24_TAG = "playback_component_block_story24_tag"
    const val SOCIAL_NEW_STYLE_STORY_TAG = "playback_component_block_social_new_style_story_tag"
    const val LONG_VIDEO_HIGHLIGHT_TAG = "playback_component_block_long_video_highlight_tag"
    const val DANMAKU_VERTICAL = "playback_component_block_danmaku_vertical"
    const val AVATAR = "playback_component_block_avatar"
    const val NICKNAME = "playback_component_block_nickname"
    const val POST_TIME = "playback_component_block_post_time"
    const val BELLOW_DESC_TIME = "playback_component_block_bellow_desc_time"
    const val COMMENT = "playback_component_block_comment"
    const val REPLY = "playback_component_block_reply"
    const val SHARE = "playback_component_block_share"
    const val COLLECT = "playback_component_block_collect"
}
