name: Release Notify

on:
  release:
    types: [ published ]

permissions: { }

jobs:
  send-release-message:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Telegram on Release
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          RELEASE_URL: ${{ github.event.release.html_url }}
          RELEASE_MESSAGE: |+
            New release published on github!

            Name: ${{ github.event.release.name }}
            Tag: ${{ github.event.release.tag_name }}

            Changelog:
            ${{ github.event.release.body }}

            View release: ${{ github.event.release.html_url }}
        run: |
          ESCAPED=`python3 -c 'import os,urllib.parse; msg = os.environ["RELEASE_MESSAGE"]; print(urllib.parse.quote(msg[:4096]))'`
          curl -v "https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage?chat_id=${TG_CHAT_ID}&text=${ESCAPED}"